### ISSUE TITLE
Where can I get file 'ihm_normalizer'

### ISSUE THREAD

**Issue by LucasWang16** [choczhang/ConCare#1]
Hi,
I get trouble when I run the notebook in this project. I can't find the file 'ihm_normalizer', which should stay in ./data/ dictionary. Can you tell me where can I get this file, please?
Thanks!
Lucas

**Comment by choczhang** [comment]
The preprocessing code of the dataset is from a benchmark, you can get the 'ihm' at https://github.com/YerevaNN/mimic3-benchmarks/blob/master/mimic3benchmark/readers.py

And the whole preprocessing code is available at https://github.com/YerevaNN/mimic3-benchmarks

**Comment by LucasWang16** [comment]
Thank you for your reply. I read the source code in readers.py and I think the 'ihm_normalizer' is your pre-defined parameters for batch generation. If you can provide this file, it will help me a lot. And after completing the 'Train / validation split', I still can not get the '/data/demographic/' dictionary and I check  YerevaNN's code but can not get solution. Please tell me how to get it if you know the solution.
