### ISSUE TITLE
Can not find file ihm_normalizer and demographic

### ISSUE THREAD

**Issue by ruilialice** [choczhang/ConCare#2]
Hi,
Thanks for sharing your code~ Great work~

But when running your code, I can not find file "ihm_normalizer", which is used to normalize the data. I ran the benchmark code: [https://github.com/YerevaNN/mimic3-benchmarks](url) , but there is no file named "ihm_normalizer". Instead, there are three files in [https://github.com/YerevaNN/mimic3-benchmarks/tree/master/mimic3models/in_hospital_mortality](url) named very likely with "ihm_normalizer", they are "ihm_ts2.0.input_str:previous.start_time:zero.normalizer", ... . Are these files related with "ihm_normalizer"?

Another question is that you use the "demographic" file, which contains the static baseline information about patients, but it seems that the benchmark does not contain this file and you do not public these file as well. Is it possible to release this file? The paper does not clearly defines what kinds of demographic information is used and what kind of primary disease is use.

Thanks~

Thanks~

**Comment by gogh-hong** [comment]
> Hi,
> Thanks for sharing your code~ Great work~
> 
> But when running your code, I can not find file "ihm_normalizer", which is used to normalize the data. I ran the benchmark code: [https://github.com/YerevaNN/mimic3-benchmarks](url) , but there is no file named "ihm_normalizer". Instead, there are three files in [https://github.com/YerevaNN/mimic3-benchmarks/tree/master/mimic3models/in_hospital_mortality](url) named very likely with "ihm_normalizer", they are "ihm_ts2.0.input_str:previous.start_time:zero.normalizer", ... . Are these files related with "ihm_normalizer"?
> 
> Another question is that you use the "demographic" file, which contains the static baseline information about patients, but it seems that the benchmark does not contain this file and you do not public these file as well. Is it possible to release this file? The paper does not clearly defines what kinds of demographic information is used and what kind of primary disease is use.
> 
> Thanks~
> 
> Thanks~

Have you solved this problem

**Comment by ruilialice** [comment]
> > Hi,
> 
> > Thanks for sharing your code~ Great work~
> 
> > 
> 
> > But when running your code, I can not find file "ihm_normalizer", which is used to normalize the data. I ran the benchmark code: [https://github.com/YerevaNN/mimic3-benchmarks](url) , but there is no file named "ihm_normalizer". Instead, there are three files in [https://github.com/YerevaNN/mimic3-benchmarks/tree/master/mimic3models/in_hospital_mortality](url) named very likely with "ihm_normalizer", they are "ihm_ts2.0.input_str:previous.start_time:zero.normalizer", ... . Are these files related with "ihm_normalizer"?
> 
> > 
> 
> > Another question is that you use the "demographic" file, which contains the static baseline information about patients, but it seems that the benchmark does not contain this file and you do not public these file as well. Is it possible to release this file? The paper does not clearly defines what kinds of demographic information is used and what kind of primary disease is use.
> 
> > 
> 
> > Thanks~
> 
> > 
> 
> > Thanks~
> 
> 
> 
> Have you solved this problem

Nope, I haven't solved this problem.

**Comment by massltime** [comment]
> Hi, Thanks for sharing your code~ Great work~
> 
> But when running your code, I can not find file "ihm_normalizer", which is used to normalize the data. I ran the benchmark code: [https://github.com/YerevaNN/mimic3-benchmarks](url) , but there is no file named "ihm_normalizer". Instead, there are three files in [https://github.com/YerevaNN/mimic3-benchmarks/tree/master/mimic3models/in_hospital_mortality](url) named very likely with "ihm_normalizer", they are "ihm_ts2.0.input_str:previous.start_time:zero.normalizer", ... . Are these files related with "ihm_normalizer"?
> 
> Another question is that you use the "demographic" file, which contains the static baseline information about patients, but it seems that the benchmark does not contain this file and you do not public these file as well. Is it possible to release this file? The paper does not clearly defines what kinds of demographic information is used and what kind of primary disease is use.
> 
> Thanks~
> 
> Thanks~

Thanks for your interest in our work! We have uploaded the demographic (static baseline) information of patients to Google Drive. You can download it from this link directly. https://drive.google.com/file/d/1TXn4UdtQCzfd7TdDJAo_6_IcnO2LUa1a/view?usp=sharing

**Comment by massltime** [comment]
> > Hi,
> > Thanks for sharing your code~ Great work~
> > But when running your code, I can not find file "ihm_normalizer", which is used to normalize the data. I ran the benchmark code: [https://github.com/YerevaNN/mimic3-benchmarks](url) , but there is no file named "ihm_normalizer". Instead, there are three files in [https://github.com/YerevaNN/mimic3-benchmarks/tree/master/mimic3models/in_hospital_mortality](url) named very likely with "ihm_normalizer", they are "ihm_ts2.0.input_str:previous.start_time:zero.normalizer", ... . Are these files related with "ihm_normalizer"?
> > Another question is that you use the "demographic" file, which contains the static baseline information about patients, but it seems that the benchmark does not contain this file and you do not public these file as well. Is it possible to release this file? The paper does not clearly defines what kinds of demographic information is used and what kind of primary disease is use.
> > Thanks~
> > Thanks~
> 
> Have you solved this problem

Thanks for your interest in our work! We have uploaded the demographic (static baseline) information of patients to Google Drive. You can download it from this link directly. https://drive.google.com/file/d/1TXn4UdtQCzfd7TdDJAo_6_IcnO2LUa1a/view?usp=sharing

**Comment by choczhang** [comment]
Thank you for your interest in our work, we have updated the information.
