### ISSUE TITLE
how to generate demographic folder

### ISSUE THREAD

**Issue by tianxu08** [choczhang/ConCare#3]
Hi 
Thanks so much for sharing the code. Very helpful. 
I'm wondering how to generate the `demographic` data for 
`demo_path = data_path + 'demographic/'`

From the episode.csv, i saw

> Icustay,Ethnicity,Gender,Age,Height,Weight,Length of Stay,Mortality,Diagnosis 4019,Diagnosis 4280....

Maybe it is related to demographic. I'm not sure whether my guess is right.  

Thanks a lot.

**Comment by ixuejiaozhao** [comment]
Meet same issue~ Hope for the answer of authors. Thank you very much.

**Comment by massltime** [comment]
> Hi Thanks so much for sharing the code. Very helpful. I'm wondering how to generate the `demographic` data for `demo_path = data_path + 'demographic/'`
> 
> From the episode.csv, i saw
> 
> > Icustay,Ethnicity,Gender,Age,Height,Weight,Length of Stay,Mortality,Diagnosis 4019,Diagnosis 4280....
> 
> Maybe it is related to demographic. I'm not sure whether my guess is right.
> 
> Thanks a lot.

Thanks for your interest in our work! We have uploaded the demographic (static baseline) information of patients to Google Drive. You can download it from this link directly. https://drive.google.com/file/d/1TXn4UdtQCzfd7TdDJAo_6_IcnO2LUa1a/view?usp=sharing

**Comment by tianxu08** [comment]
Thanks so much. It helps a lot.

**Comment by choczhang** [comment]
Thank you for your interest in our work, we have updated the information.
